/**
 * Single cases of the temperature tower that the two real sample files do not
 * show: a tower sliced short, a tower without a base plate, a stray temperature
 * command in the body, relative instead of absolute E counting, a range outside
 * the bands, the top cap. Run: node tools/test_tt.mjs
 */
import { findLayers, buildTtPlan, bandTemp, BANDS, TEMPS } from '../js/tt/layers.js';
import { generateTt } from '../js/tt/generator.js';
import { adviceText } from '../js/tt/result.js';

let failed = 0;

/** Only the print's temperature commands — the `M104 S0` in the end block does not count. */
function tempCommands(lines) {
  const end = lines.indexOf('; Filament-specific end gcode');
  return lines.slice(0, end < 0 ? lines.length : end)
    .filter(l => /^M10[49] [SR]\d+$/.test(l));
}

function check(name, ok, detail) {
  console.log((ok ? 'PASS  ' : 'FAIL  ') + name.padEnd(50) + (detail || ''));
  if (!ok) failed++;
}

/** Minimal SourceDocument, only as much as the TT test really reads. */
function makeDoc(raw, opts) {
  const o = opts || {};
  return {
    raw,
    settings: new Map(),
    printer: { flavor: o.flavor || 'klipper', relativeE: !!o.relativeE, bed: { x: 250, y: 250 } },
    material: {
      temperature: o.temperature === undefined ? 180 : o.temperature,
      firstLayerTemperature: o.firstLayerTemperature,
      filamentDiameter: 1.75, density: 1.24, cost: 25, filamentName: 'Test',
    },
    geometry: { layerHeight: 0.3, firstLayerHeight: 0.2, lineWidth: 0.45 },
    speeds: { firstLayer: 20 },
    fan: { disableFirstLayers: 1 },
    issues: [],
  };
}

/**
 * A miniature tower: a base plate, above it `middle` narrower base layers, on
 * top `bands` bands of `perBand` layers each. The plate is wider than
 * everything else, within a band the width grows and drops back at the
 * boundary — the same feature the detection relies on in the real model.
 */
function tower(opts) {
  const o = opts || {};
  const bands = o.bands === undefined ? BANDS : o.bands;
  const perBand = o.perBand || 4;
  const lh = 0.3, flh = 0.2;
  const L = [
    '; generated by PrusaSlicer',
    "EXCLUDE_OBJECT_DEFINE NAME='tower_stl'",
    'M82',
    'M73 P0 R' + (bands * perBand + 1),
    'G92 E0',
  ];
  let z = 0, e = 0, n = 0;
  const layer = (h, w, mark, sparse) => {
    z = +(z + h).toFixed(5);
    L.push(';LAYER_CHANGE', ';Z:' + z, ';HEIGHT:' + h);
    if (mark) L.push("EXCLUDE_OBJECT_START NAME='tower_stl'");
    if (sparse) L.push(';TYPE:Internal infill');
    L.push('G92 E0');
    e = 1;
    L.push('G1 X0 Y0 F1200');
    L.push('G1 X' + w + ' Y0 E' + e + ' F1200');
    e = +(e + 1).toFixed(5);
    L.push('G1 X' + w + ' Y5 E' + e);
    L.push('G1 E' + (e - 0.5).toFixed(5));       // retract
    L.push('M73 P' + Math.round(n / (bands * perBand + 1) * 100)
      + ' R' + (bands * perBand + 1 - n));
    n++;
  };

  if (!o.noFoot) {
    layer(flh, 60, true);                        // base plate, wider than everything
    const middle = o.middle === undefined ? 1 : o.middle;
    for (let k = 0; k < middle; k++) layer(lh, 40, false);   // smaller step
  }
  // With `cap` the topmost layers carry no sparse infill any more -- the
  // signature of the real model, and what the top cap is found by.
  const cap = o.cap || 0;
  for (let b = 0; b < bands; b++) {
    for (let k = 0; k < perBand; k++) {
      const solidTop = b === bands - 1 && k >= perBand - cap;
      layer(lh, 10 + k * 4, o.noFoot && n === 0, cap > 0 && !solidTop);
      if (o.strayTemp && n === 4) L.push('M104 S222');
    }
  }
  L.push("EXCLUDE_OBJECT_END NAME='tower_stl'");
  L.push('; Filament-specific end gcode');
  L.push('M104 S0');
  L.push('; filament used [mm] = 999');
  L.push('; estimated printing time (normal mode) = 1h 0m 0s');
  return L;
}

/* --- 1) The fixed band -> temperature mapping ----------------------------- */
{
  check('band 1 is 180 C, the top band is 280 C',
    bandTemp(1) === 180 && bandTemp(BANDS) === 280 && BANDS === 21, TEMPS.join(' '));
  check('the steps are 5 C',
    TEMPS.every((t, i) => i === 0 || t - TEMPS[i - 1] === 5));
}

/* --- 2) A complete tower is recognized ------------------------------------ */
{
  const raw = tower();
  const found = findLayers(raw, makeDoc(raw));
  check('all bands found in a complete tower',
    found.bands.length === BANDS && found.issues.length === 0,
    found.issues.map(i => i.code).join(','));
  check('neither base section is counted as a band',
    found.foot && found.foot.first === 0 && found.foot.last === 1,
    JSON.stringify(found.foot));
  check('every layer above the base belongs to a band',
    found.layers.slice(found.foot.last + 1).every(l => l.band >= 1 && l.band <= BANDS));
}

/* --- 3) A tower that is too short is an error ----------------------------- */
{
  const raw = tower({ bands: BANDS - 4 });
  const found = findLayers(raw, makeDoc(raw));
  check('a tower cut short is refused',
    found.bands.length === 0 && found.issues.some(i => i.code === 'E21'),
    found.issues.map(i => i.code + ':' + i.level).join(','));
}

/* --- 3b) A tower without a base --------------------------------------------
   Without it a cut downwards would find no first layer. The smaller step
   counts too: the generator takes the missing layers from it. */
{
  const raw = tower({ noFoot: true });
  const found = findLayers(raw, makeDoc(raw));
  check('a tower without any base is refused',
    found.bands.length === 0 && found.issues.some(i => i.code === 'E23'),
    found.issues.map(i => i.code).join(','));

  const flat = tower({ middle: 0 });
  const one = findLayers(flat, makeDoc(flat));
  check('a base without its upper section is refused',
    one.bands.length === 0 && one.issues.some(i => i.code === 'E23'),
    one.issues.map(i => i.code).join(','));
}

/* --- 4) Whole tower: base plate plus all bands ---------------------------- */
{
  const raw = tower();
  const doc = makeDoc(raw);
  const plan = buildTtPlan(raw, doc, { from: TEMPS[0], to: TEMPS[TEMPS.length - 1] });
  const res = generateTt(plan);
  const zs = res.lines.filter(l => l.startsWith(';Z:')).map(l => parseFloat(l.slice(3)));
  check('the whole tower keeps every layer, one base layer added',
    zs.length === plan.layers.length + 1, zs.length + ' vs ' + plan.layers.length);
  check('the base sits at first_layer_height', zs[0] === 0.2, String(zs[0]));
  check('the missing base layer is a repeat of the one below',
    zs[1] === 0.5 && zs[2] === 0.8, zs.slice(0, 4).join(' '));
  check('the tower moves up by the repeated layer',
    Math.abs(zs[3] - 1.1) < 1e-9, String(zs[3]));
  const temps = tempCommands(res.lines);
  check('one command per band, no wait',
    temps.length === BANDS && temps[0] === 'M104 S180'
    && temps[BANDS - 1] === 'M104 S' + bandTemp(BANDS)
    && temps.every(t => t.startsWith('M104 S')),
    temps.length + ': ' + temps.slice(0, 2).join(' ') + ' … ' + temps[temps.length - 1]);
  // The bottom switch belongs after the first layer, so the nozzle changes
  // over during the rest of the base.
  const lc = res.lines.reduce((a, l, i) => (l === ';LAYER_CHANGE' && a.push(i), a), []);
  const at = res.lines.findIndex(l => l === 'M104 S180');
  check('the bottom switch sits between the first and the second layer',
    at > lc[0] && at < lc[1], at + ' vs ' + lc.slice(0, 2).join(','));
}

/* --- 4b) If the layers suffice, nothing is repeated ----------------------- */
{
  const raw = tower({ middle: 2, perBand: 6 });
  const doc = makeDoc(raw);
  const plan = buildTtPlan(raw, doc, { from: TEMPS[0], to: TEMPS[TEMPS.length - 1] });
  const res = generateTt(plan);
  const zs = res.lines.filter(l => l.startsWith(';Z:')).map(l => parseFloat(l.slice(3)));
  check('a base that is already three layers stays as it is',
    zs.length === plan.layers.length, zs.length + ' vs ' + plan.layers.length);
  check('nothing is shifted', zs[0] === 0.2 && zs[1] === 0.5 && zs[2] === 0.8
    && Math.abs(zs[3] - 1.1) < 1e-9, zs.slice(0, 4).join(' '));
  check('the map counts three base layers, none repeated',
    res.lines.some(l => l === '; tt base = 3 layers up to Z 0.800, source layers 0-2, '
      + 'last one repeated 0x'),
    res.lines.filter(l => l.startsWith('; tt base')).join(''));
}

/* --- 5) Trimmed: Z offset and base ---------------------------------------- */
{
  const raw = tower();
  const doc = makeDoc(raw);
  const plan = buildTtPlan(raw, doc, { from: 200, to: 210 });
  const res = generateTt(plan);
  check('three bands selected', plan.printed.length === 3,
    plan.printed.map(b => b.temp).join(','));
  const zs = res.lines.filter(l => l.startsWith(';Z:')).map(l => parseFloat(l.slice(3)));
  check('the trimmed tower stands on a three layer base',
    zs[0] === 0.2 && zs[1] === 0.5 && zs[2] === 0.8, zs.slice(0, 4).join(' '));
  check('Z rises without a gap',
    zs.every((z, i) => i === 0 || z > zs[i - 1]));
  const temps = tempCommands(res.lines);
  check('the bottom band switches without waiting',
    temps[0] === 'M104 S200' && temps.length === 3,
    temps.join(' '));
  check('exactly one object bracket',
    res.lines.filter(l => /^EXCLUDE_OBJECT_START/.test(l)).length === 1 &&
    res.lines.filter(l => /^EXCLUDE_OBJECT_END/.test(l)).length === 1);
}

/* --- 6) The base plate stays as it was sliced ----------------------------- */
{
  const raw = tower();
  const doc = makeDoc(raw);
  const res = generateTt(buildTtPlan(raw, doc, { from: 200, to: 210 }));
  // The first layer: from its ;LAYER_CHANGE to the next one.
  const cut = (arr) => {
    const i = arr.indexOf(';LAYER_CHANGE');
    return arr.slice(i, arr.indexOf(';LAYER_CHANGE', i + 1));
  };
  const keep = l => !/^(EXCLUDE_OBJECT_|M486|M10[49]|M73)/.test(l) && !l.startsWith('; print_calibration_tool:');
  const a = cut(raw).filter(keep), b = cut(res.lines).filter(keep);
  check('the first base layer comes through unchanged',
    a.length > 0 && a.length === b.length && a.every((l, i) => l === b[i]),
    a.length + ' vs ' + b.length);
  // No E value is touched: the generator only tallies extrusion.
  const eOf = arr => arr.filter(l => /^G1 .*\sE/.test(l)).join('|');
  check('no extrusion value was touched in the base',
    eOf(cut(raw)) === eOf(cut(res.lines)) && eOf(cut(raw)).length > 0,
    eOf(cut(res.lines)));
}

/* --- 7) Stray temperature commands are removed ---------------------------- */
{
  const raw = tower({ strayTemp: true });
  const doc = makeDoc(raw);
  const res = generateTt(buildTtPlan(raw, doc, { from: TEMPS[0], to: TEMPS[TEMPS.length - 1] }));
  check('a stray M104 in the body is removed',
    res.stats.strippedTemp === 1 && res.lines.indexOf('M104 S222') === -1,
    'stripped ' + res.stats.strippedTemp);
}

/* --- 8) Relative E counting ----------------------------------------------- */
{
  const raw = tower().map(l => l === 'M82' ? 'M83' : l);
  const doc = makeDoc(raw, { relativeE: true });
  const res = generateTt(buildTtPlan(raw, doc, { from: 200, to: 210 }));
  // With absolute counting the generator emits a `G92 E<position>` before base
  // and body so the jump back in the layer header is right. In relative mode
  // that would be wrong and must therefore not appear.
  check('no G92 is invented in relative mode',
    res.lines.filter(l => /^G92 E/.test(l) && !/^G92 E0$/.test(l)).length === 0,
    res.lines.filter(l => /^G92 E/.test(l) && !/^G92 E0$/.test(l)).join(' '));
  check('relative mode still produces the base',
    res.lines.filter(l => l.startsWith(';Z:'))[0] === ';Z:0.2');
}

/* --- 9) Marlin uses M486 instead of EXCLUDE_OBJECT ------------------------ */
{
  const raw = tower();
  const doc = makeDoc(raw, { flavor: 'marlin2' });
  const res = generateTt(buildTtPlan(raw, doc, { from: 220, to: 230 }));
  check('marlin gets M486 S0 / S-1',
    res.lines.indexOf('M486 S0') !== -1 && res.lines.indexOf('M486 S-1') !== -1);
  // Without waiting there is no firmware branch: M104 S applies everywhere.
  check('marlin switches with M104 S as well',
    tempCommands(res.lines).every(t => t.startsWith('M104 S')),
    tempCommands(res.lines).join(' '));
}

/* --- 10) Range limits ----------------------------------------------------- */
{
  const raw = tower();
  const doc = makeDoc(raw);
  const bad = buildTtPlan(raw, doc, { from: 240, to: 200 });
  check('from above to is refused', bad.issues.some(i => i.code === 'E22'));
  const one = buildTtPlan(raw, doc, { from: 195, to: 195 });
  check('a single band works', one.printed.length === 1 && !one.hasError);
}

/* --- 10b) Top cap on a cut-short tower ------------------------------------ */
{
  const blocks = arr => {
    const out = [];
    for (let i = 0; i < arr.length; i++) {
      if (arr[i] !== ';LAYER_CHANGE') continue;
      let j = i + 1;
      while (j < arr.length && arr[j] !== ';LAYER_CHANGE'
             && arr[j] !== '; Filament-specific end gcode') j++;
      out.push(arr.slice(i, j));
    }
    return out;
  };
  const moves = b => b.filter(l => /^G1 .*X/.test(l)).join('|');

  const raw = tower({ cap: 2 });
  const doc = makeDoc(raw);
  const src = blocks(raw);

  const cut = generateTt(buildTtPlan(raw, doc, { from: 180, to: 190 }));
  const got = blocks(cut.lines);
  check('a cut-short tower is given the tower\'s own top cap',
    cut.lines.some(l => l.startsWith('; tt top cap = 2 layers')),
    cut.lines.filter(l => l.startsWith('; tt top cap')).join('') || 'no cap line');
  check('the last two layers are the ones from the top of the source',
    moves(got[got.length - 2]) === moves(src[src.length - 2])
    && moves(got[got.length - 1]) === moves(src[src.length - 1]),
    moves(got[got.length - 1]));
  // The cap is restamped onto the Z of the layers it replaces, so the layer
  // stack is the same one the tool would produce without it.
  const zOf = lines => lines.filter(l => l.startsWith(';Z:')).map(l => parseFloat(l.slice(3)));
  const bare = generateTt(buildTtPlan(tower(), makeDoc(tower()), { from: 180, to: 190 }));
  const zs = zOf(cut.lines);
  check('the layer stack is the same one as without a cap',
    zs.join(' ') === zOf(bare.lines).join(' '), zs.slice(-3).join(' '));
  check('Z still rises without a gap', zs.every((z, i) => i === 0 || z > zs[i - 1]));
  check('the topmost band still gets its temperature',
    tempCommands(cut.lines).join(' ') === 'M104 S180 M104 S185 M104 S190',
    tempCommands(cut.lines).join(' '));

  // Absolute counting: the retract in the copied layer head is an absolute
  // value from the top of the source and needs the counter set to match.
  const g92 = cut.lines.filter(l => / top cap$/.test(l));
  check('absolute counting gets the E counter set before the cap',
    g92.length === 1 && /^G92 E/.test(g92[0]), g92.join('') || 'none');
  const rel = generateTt(buildTtPlan(raw, makeDoc(raw, { relativeE: true }),
    { from: 180, to: 190 }));
  check('relative counting needs none',
    !rel.lines.some(l => / top cap$/.test(l))
    && rel.lines.some(l => l.startsWith('; tt top cap')));

  // Nothing is cut off above: the top is the real one, there is nothing to copy.
  const whole = generateTt(buildTtPlan(raw, doc, { from: 180, to: 280 }));
  check('an untrimmed top gets no cap',
    !whole.lines.some(l => l.startsWith('; tt top cap')));

  // A source without sparse infill has no cap to take -- the older behaviour.
  const plain = generateTt(buildTtPlan(tower(), makeDoc(tower()), { from: 180, to: 190 }));
  check('a source without sparse infill is left as it was',
    !plain.lines.some(l => l.startsWith('; tt top cap')));
}

/* --- 11) The advice names the temperature --------------------------------- */
{
  const raw = tower();
  const text = adviceText(makeDoc(raw), 225);
  check('the advice names the temperature', text.indexOf('225') !== -1);
}

console.log('');
console.log(failed ? failed + ' check(s) failed' : 'all checks passed');
process.exit(failed ? 1 : 0);
